# Generated by Django 4.1.2 on 2022-11-04 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('triangle', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Logg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=255)),
                ('method', models.CharField(choices=[('post', 'post'), ('get', 'get'), ('put', 'put'), ('patch', 'patch'), ('delete', 'delete')], default='post', max_length=35)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('date', models.JSONField()),
            ],
        ),
    ]
