# Generated by Django 4.1.2 on 2022-11-04 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('triangle', '0002_logg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logg',
            name='date',
            field=models.JSONField(default=dict),
        ),
    ]
