# Generated by Django 4.1.2 on 2022-11-04 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('triangle', '0003_alter_logg_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logg',
            name='method',
            field=models.CharField(choices=[('POST', 'post'), ('GET', 'get'), ('PUT', 'put'), ('PATCH', 'patch'), ('DELETE', 'delete')], default='POST', max_length=35),
        ),
    ]
