# Generated by Django 4.1.2 on 2022-10-26 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_car_id_alter_car_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='comment',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
